### ISSUE TITLE
Unable to load mod for multiplayer

### ISSUE THREAD

**Issue by Shoopz** [Kinoler/RecipeBrowserToMagicStorage#1]
I wanted to use this mod personally with my friends, but due to it being purely server side instead of a client side mod, I was unable to get any use out of it. Could I request it be made into a client side mod? There's no reason it would need the other players to use it as well.

**Comment by Kinoler** [comment]
Sorry, but it's been too long since I did this. Therefore, I just do not understand what I should fix and what actually makes the mod server-side. If you write down how to fix it, then I will fix it.

**Comment by Kinoler** [comment]
The mod moved to client side mod
