### ISSUE TITLE
update to tmodloader 11.8.4

### ISSUE THREAD

**Issue by milkev** [Kinoler/RecipeBrowserToMagicStorage#2]
mod is currently unusable due to being outdated (tmodloader automatically disables it due to being marked for an older version)

**Comment by Kinoler** [comment]
What the version of terraria do you use?

**Comment by milkev** [comment]
![image](https://user-images.githubusercontent.com/22010128/121751101-c909cf80-caca-11eb-964c-33f4782189e0.png)

**Comment by Kinoler** [comment]
hmmm, it's mine, works fine
![image](https://user-images.githubusercontent.com/37263494/121779192-19546080-cba3-11eb-93ac-826e78b6fc9a.png)

Could you send a screenshot of error where the tmodloader automatically disables it. Or some more info. Because I cant reproduce it on my side.
