### ISSUE TITLE
New bug after the new update

### ISSUE THREAD

**Issue by pourquoiLaVie** [Kinoler/RecipeBrowserToMagicStorage#5]
I just loaded my moderatly (?) modded terraria, and a warning concerning new updates came (classic you will say), it only contained the information that this mod was updated. 
While loading the mods, an issue came : 
![image](https://user-images.githubusercontent.com/47030525/184504204-fffeb6ef-8e69-4e48-acde-3d1760e86a6f.png)

When i disabled it, evrything loaded fine. If you need it, i can also give you my list of mods.

**Comment by Kinoler** [comment]
Update MagicStorage to the latest version
